import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins ({
  weight: ["300", "400", "500", "600", "800"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Reload Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${poppins.className} antialiased dark bg-zinc-900 text-white`}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
